// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token: string | undefined;
    try {
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token;
    } catch {
      // ignore
    }

    let guestId: string | null = null;
    if (typeof window !== "undefined") {
      guestId = localStorage.getItem("vd_guest_id");
      if (!guestId) {
        guestId = crypto.randomUUID();
        localStorage.setItem("vd_guest_id", guestId);
      }
    }

    const headers: Record<string, string> = {};
    if (token) {
      headers["Authorization"] = `Bearer ${token}`;
    }
    if (guestId) {
      headers["x-guest-id"] = guestId;
    }

    return next({
      headers,
    });
  },
);
